name: CICD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout source
              uses: actions/checkout@v3
            - name: Setup java
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'
            - name: Build Project
              run: mvn clean install -DskipTests
            - name: Login to docker hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker buildx build --platform linux/amd64 -t flavienlm/employe-backend:test .
            - name: Publish image to docker hub
              run: docker push flavienlm/employe-backend:test
    deploy:
        needs: build
        runs-on: [self-hosted]
        steps:
          - name: Pull Image from focker hub
            run: docker pull flavienlm/employe-backend:test
          - name: Delete old container
            run: docker rm -f test
          - name: 
            run: docker run -d -p 80:80 --name test flavienlm/employe-backend:test



                